// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    return $('#nav > ul > li').click(function() {
      var section;
      section = $(this).html();
      $('.active').removeClass('active');
      $(this).addClass('active');
      return $("#" + section).addClass('active');
    });
  });

}).call(this);
